import os
import tempfile

import streamlit as st

from llama_index import (
    ServiceContext,
    StorageContext,
    VectorStoreIndex,
    download_loader,
)
from llama_index.chat_engine.simple import SimpleChatEngine
from llama_index.llms import OpenAI
from llama_index.vector_stores.couchbase_store import CouchbaseVectorStore


def store_document(uploaded_file, storage_context, service_context):
    """Chunk the PDF & store it in Couchbase Vector Store."""
    if uploaded_file is not None:
        temp_dir = tempfile.TemporaryDirectory()
        temp_file_path = os.path.join(temp_dir.name, uploaded_file.name)

        with open(temp_file_path, "wb") as f:
            f.write(uploaded_file.getvalue())

        PDFReader = download_loader("PDFReader", custom_path=temp_dir.name)

        loader = PDFReader()
        documents = loader.load_data(file=temp_file_path)

        index = VectorStoreIndex.from_documents(
            documents,
            service_context=service_context,
            storage_context=storage_context,
        )
        st.info(f"PDF loaded into vector store in {len(documents)} documents")
        return index
    return None


@st.cache_resource(show_spinner="Connecting to Couchbase")
def get_vector_store(
    db_conn_str,
    db_username,
    db_password,
    db_bucket,
    db_scope,
    db_collection,
    index_name,
):
    """Return the Couchbase vector store."""
    return CouchbaseVectorStore(
        connection_string=db_conn_str,
        db_username=db_username,
        db_password=db_password,
        bucket_name=db_bucket,
        scope_name=db_scope,
        collection_name=db_collection,
        index_name=index_name,
    )


if __name__ == "__main__":
    # Authorization
    if "auth" not in st.session_state:
        st.session_state.auth = False

    st.set_page_config(
        page_title="Chat with your PDF using LlamaIndex, Couchbase & OpenAI",
        page_icon="🤖",
        layout="centered",
        initial_sidebar_state="auto",
        menu_items=None,
    )

    AUTH = os.getenv("LOGIN_PASSWORD")
    user_pwd = st.text_input("Enter password", type="password")
    pwd_submit = st.button("Submit")

    if pwd_submit and user_pwd == AUTH:
        st.session_state.auth = True
    elif pwd_submit and user_pwd != AUTH:
        st.error("Incorrect password")

    if st.session_state.auth:
        # Load environment variables
        DB_CONN_STR = os.getenv("DB_CONN_STR")
        DB_USERNAME = os.getenv("DB_USERNAME")
        DB_PASSWORD = os.getenv("DB_PASSWORD")
        DB_BUCKET = os.getenv("DB_BUCKET")
        DB_SCOPE = os.getenv("DB_SCOPE")
        DB_COLLECTION = os.getenv("DB_COLLECTION")
        INDEX_NAME = os.getenv("INDEX_NAME")

        vector_store = get_vector_store(
            DB_CONN_STR,
            DB_USERNAME,
            DB_PASSWORD,
            DB_BUCKET,
            DB_SCOPE,
            DB_COLLECTION,
            INDEX_NAME,
        )

        # Build the prompt for the RAG
        template_rag = """You are a helpful bot. If you cannot answer based on the context provided, respond with a generic answer. Answer the question as truthfully as possible using the context below:
        {context}

        Question: {question}"""

        # Pure OpenAI prompt without RAG
        template_without_rag = """You are a helpful bot. Answer the question as truthfully as possible.

        Question: {question}"""

        # Frontend
        couchbase_logo = (
            "https://emoji.slack-edge.com/T024FJS4M/couchbase/4a361e948b15ed91.png"
        )

        st.title("Chat with PDF")
        st.markdown(
            "Answers with [Couchbase logo](https://emoji.slack-edge.com/T024FJS4M/couchbase/4a361e948b15ed91.png) are generated using *RAG* while 🤖 are generated by pure *LLM (ChatGPT)*"
        )

        # Use OpenAI as the llm
        llm = OpenAI(temperature=0, model="gpt-4-1106-preview")
        service_context = ServiceContext.from_defaults(
            llm=llm, chunk_size=1500, chunk_overlap=150
        )
        storage_context = StorageContext.from_defaults(vector_store=vector_store)

        # Pure LLM for comparison of results
        pure_llm = OpenAI(model="gpt-4-1106-preview")
        st.session_state.chat_llm = SimpleChatEngine.from_defaults(
            llm=pure_llm,
            system_prompt=template_without_rag,
        )

        with st.sidebar:
            st.header("Upload your PDF")
            with st.form("upload pdf"):
                uploaded_file = st.file_uploader(
                    "Choose a PDF.",
                    help="The document will be deleted after one hour of inactivity (TTL).",
                    type="pdf",
                )
                submitted = st.form_submit_button("Upload")
                if submitted:
                    index = store_document(
                        uploaded_file, storage_context, service_context
                    )
                    if not index:
                        st.warning("Please upload a valid PDF")

                    # Create the chat engine with context from the uploaded data
                    st.session_state.chat_engine_rag = index.as_chat_engine(
                        chat_mode="context",
                        system_prompt=template_rag,
                    )

            st.subheader("How does it work?")
            st.markdown(
                """
                For each question, you will get two answers:
                * one using RAG ([Couchbase logo](https://emoji.slack-edge.com/T024FJS4M/couchbase/4a361e948b15ed91.png))
                * one using pure LLM - OpenAI (🤖).
                """
            )

            st.markdown(
                "For RAG, we are using [LlamaIndex](https://www.llamaindex.ai/), [Couchbase Vector Search](https://couchbase.com/) & [OpenAI](https://openai.com/). We fetch parts of the PDF relevant to the question using Vector search & add it as the context to the LLM. The LLM is instructed to answer based on the context from the Vector Store."
            )

            # View Code
            if st.checkbox("View Code"):
                st.write(
                    "View the code here: [Github](https://github.com/couchbase-examples/rag-demo-llama-index/blob/main/chat_with_pdf.py)"
                )

        if "messages" not in st.session_state:
            st.session_state.messages = []
            st.session_state.messages.append(
                {
                    "role": "assistant",
                    "content": "Hi, I'm a chatbot who can chat with the PDF. How can I help you?",
                    "avatar": "🤖",
                }
            )
            st.session_state.chat_llm = None
            st.session_state.chat_engine_rag = None

        # Display chat messages from history on app rerun
        for message in st.session_state.messages:
            with st.chat_message(message["role"], avatar=message["avatar"]):
                st.markdown(message["content"])

        # React to user input
        if question := st.chat_input("Ask a question based on the PDF"):
            # Display user message in chat message container
            st.chat_message("user").markdown(question)

            # Add user message to chat history
            st.session_state.messages.append(
                {"role": "user", "content": question, "avatar": "👤"}
            )

            # Add placeholder for streaming the response
            with st.chat_message("assistant", avatar=couchbase_logo):
                message_placeholder = st.empty()

            # stream the response from the RAG
            rag_response = ""
            rag_stream_response = st.session_state.chat_engine_rag.stream_chat(question)
            for chunk in rag_stream_response.response_gen:
                rag_response += chunk
                message_placeholder.markdown(rag_response + "▌")

            message_placeholder.markdown(rag_response)
            st.session_state.messages.append(
                {
                    "role": "assistant",
                    "content": rag_response,
                    "avatar": couchbase_logo,
                }
            )

            # stream the response from the pure LLM

            # Add placeholder for streaming the response
            with st.chat_message("ai", avatar="🤖"):
                message_placeholder_pure_llm = st.empty()

            pure_llm_response = ""
            pure_llm_stream_response = st.session_state.chat_llm.stream_chat(question)

            for chunk in pure_llm_stream_response.response_gen:
                pure_llm_response += chunk
                message_placeholder_pure_llm.markdown(pure_llm_response + "▌")

            message_placeholder_pure_llm.markdown(pure_llm_response)
            st.session_state.messages.append(
                {
                    "role": "assistant",
                    "content": pure_llm_response,
                    "avatar": "🤖",
                }
            )
